// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::chassisleftMotor = NULL;
SpeedController* RobotMap::chassisrightMotor = NULL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	if (TESTERBOT != 1) {
		chassisleftMotor = new Talon(0);
		lw->AddActuator("Chassis", "leftMotor", (Talon*) chassisleftMotor);

		chassisrightMotor = new Talon(1);
		lw->AddActuator("Chassis", "rightMotor", (Talon*) chassisrightMotor);
	} else {
		chassisleftMotor = new Jaguar(0);
		lw->AddActuator("Chassis", "leftMotor", (Jaguar*) chassisleftMotor);

		chassisrightMotor = new Jaguar(1);
		lw->AddActuator("Chassis", "rightMotor", (Jaguar*) chassisrightMotor);
	}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
