// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::chassisFrontLeftMotor = NULL;
SpeedController* RobotMap::chassisFrontRightMotor = NULL;
SpeedController* RobotMap::chassisBackLeftMotor = NULL;
SpeedController* RobotMap::chassisBackRightMotor = NULL;


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
Talon* RobotMap::winchtalon = NULL;

Gyro* RobotMap::chassisGyro = NULL;


void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	
	chassisFrontLeftMotor = new Talon(CHASSIS_FRONT_LEFT_MOTOR_PWM);
	lw->AddActuator("Chassis", "leftMotor", (Talon*) chassisFrontLeftMotor);

	chassisFrontRightMotor = new Talon(CHASSIS_FRONT_RIGHT_MOTOR_PWM);
	lw->AddActuator("Chassis", "rightMotor", (Talon*) chassisFrontRightMotor);

	chassisBackLeftMotor = new Talon(CHASSIS_BACK_LEFT_MOTOR_PWM);
	lw->AddActuator("Chassis", "leftMotor", (Talon*) chassisBackLeftMotor);

	chassisBackRightMotor = new Talon(CHASSIS_BACK_RIGHT_MOTOR_PWM);
	lw->AddActuator("Chassis", "rightMotor", (Talon*) chassisBackRightMotor);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	winchtalon = new Talon(WINCH_TALON_MOTOR_PWM);
	chassisGyro = new Gyro(CHASSIS_GYRO_ANALOG_INPUT);
}
